In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
np.save("a.npy", a)

In [3]:
aa = np.load("a.npy")
aa

array([1, 2, 3, 4])

In [4]:
b = np.zeros(shape=(10,))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
b[:len(aa)] = aa
b

array([1., 2., 3., 4., 0., 0., 0., 0., 0., 0.])

In [7]:

x =np.arange(0,11)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])