In [1]:
import torch as th
import numpy as np

In [3]:
dg = th.tensor([1,2,3])
dg

tensor([1, 2, 3])

In [ ]:
a = dg.reshape((1, -1))

tensor([[1, 2, 3]])

In [6]:
b = a.repeat((10, 1))
b

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [7]:
a

tensor([[1, 2, 3]])

In [8]:
b

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [39]:
a = th.tensor([1,2,3])
b = th.tensor([4,5,6])
a, b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [40]:
a.sum(axis=-1)

tensor(6)

In [42]:
c = th.concat([a.sum(axis=-1).reshape((-1)), b.sum(axis=-1).reshape((-1))]).float()
c

tensor([ 6., 15.])

In [43]:
c.mean()

tensor(10.5000)